## statistical simulations jl (2016, EconometricsBySimulation gist)

In [1]:
using Distributions

n = 10_000
x1 = rand(Normal(), n)
x2 = rand(Normal(), n) .+ .2 * x1
x3 = 1000*(rand(Normal(), n) .- .2*x1 .+ .2*x2)

10000-element Vector{Float64}:
   206.52741912624907
   318.96591758711156
  -734.0020163603923
 -1006.229643232553
  1164.9326359706304
   523.6833800366632
   196.37303153372127
  -236.90198034985815
 -1031.55895582562
  -882.9770690674358
     ⋮
  -765.8818638548604
  -311.5040330333324
  -606.0758512539036
   832.8372106963363
  1034.073199131053
  1174.9887588786041
   377.900765595268
   -12.115355127540523
  1829.4444876185005

In [2]:
x2 = rand(Normal(), n)
x3 = rand(Normal(), n)

u = rand(Normal(), n) .* 2

10000-element Vector{Float64}:
 -1.8932646472079133
  1.6099982288418806
  2.897414988049849
 -0.443220948861189
 -2.1233740976848865
  1.602844259527982
  2.5763457993104817
 -0.21416089005439434
  1.2881461201530489
  0.44507411917521605
  ⋮
 -1.5212181502356312
 -3.4759162424468415
 -1.2913996555065077
  0.0688844262863453
  1.9521910643601954
 -1.4307912612596532
 -0.6103424560623045
 -0.42935494978692695
 -1.3824372261358386

In [3]:
y = 2 .+ 1.5*x1 .+ 2.7*x2 .- .5*x3 + u

10000-element Vector{Float64}:
  2.6258450138744305
  1.849012256799187
  4.457632014985222
  1.7834973806478636
 -5.20457221219432
  7.776732496639692
  3.225466206954068
 -1.7245021752045757
 -0.31647824741817776
  5.848254864464986
  ⋮
  1.0834334679902256
 -2.2364243326763624
  2.4688879260328065
 -1.91207394729345
  3.9440268145752952
 -1.9777353058812213
  3.7168236663901197
 -2.807476973298145
 -3.4093629553308142

In [4]:
constant = fill(1, n)
X = hcat(constant, x1, x2, x3)

10000×4 Matrix{Float64}:
 1.0   1.55445     0.159405    0.485924
 1.0  -0.803783   -0.164242    0.223712
 1.0  -0.472934   -0.100318   -1.08095
 1.0   0.84418    -0.699377   -1.69753
 1.0  -1.53253    -1.30816    -1.49925
 1.0   0.861405    1.21114     0.776618
 1.0   0.0705093  -0.303228    1.27586
 1.0   0.322919   -1.74172    -1.41586
 1.0   0.529869   -1.91237    -1.52793
 1.0  -0.0403974   1.28709     0.022751
 ⋮                            
 1.0   0.606156    0.0365878   0.806739
 1.0  -0.794613    0.0059272  -0.830816
 1.0   0.216039    0.522416   -0.0514105
 1.0   0.0488399  -1.26587     1.27272
 1.0   0.763454   -0.076007    1.89625
 1.0  -1.5109      0.0247162   0.694647
 1.0  -0.0534039   0.686391   -1.10803
 1.0  -1.05499    -0.930096    0.568761
 1.0   0.857983   -2.0035     -0.191085

In [5]:
β = inv(X'X) * X'y

ŷ = X*β

s² = ((y - ŷ)' * (y - ŷ)) / (n - 4)

4.052995715461393

In [6]:
seβ₁ = √(s² * inv(x1' * x1))
seβ₂ = √(s² * inv(x2' * x2))
seβ₃ = √(s² * inv(x3' * x3))

√(s² .* inv(X'X))

ccdf(Chisq(4), s²)

0.3988811687154617

In [ ]:
# -> *** |> <| <*> ## $$ @@= != =!= ~> .- ... $= /= ==> <= >= == === !== << >> >>> <<< && ||